version: '3.4'

services:

  hotel:
    image: hotel
    build:
      context: .
      dockerfile: Hotel.Web.Api/Dockerfile
    depends_on:
      - data.mysql

  data.mysql:
    image: mysql/mysql-server:8.0.16
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: hotel_db
      MYSQL_USER: owner
      MYSQL_PASSWORD: hotel_db_owner$pass
    volumes:
    - dbdata:/var/lib/mysql

volumes:
  dbdata: